# Generated by Django 4.2.7 on 2023-11-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0002_resgister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resgister',
            old_name='password1',
            new_name='password',
        ),
    ]
